### ISSUE TITLE
On Dashboard, Category isn't a link

### ISSUE THREAD

**Issue by srikanthvejendla** [anshooarora/extentx#56]
It would be helpful if we can quickly navigate from dashboard screen

![image](https://cloud.githubusercontent.com/assets/1727652/18041195/e4fc8196-6d6a-11e6-9e1c-a95eac1c494d.png)

**Comment by anshooarora** [comment]
The issue with this approach is, categories are part of Reports and there is no particular location where navigation will direct you to when there are multiple reports - especially, since each report will possibly have the same set of categories.  If you have any suggestions, please share and I will mark this an an enhancement.  Otherwise, we can mark this as closed.
